### ISSUE TITLE
Remove gfold-bin (but keep the other two gfold packages!)

### ISSUE THREAD

**Issue by nickgerace** [orhun/PKGBUILDs#5]
Hi! `gfold 1.0.0` has shipped, but has removed support for uploaded binaries. This is due to lack of popularity and maintenance. The package-manager-driven options are prefered and tested.

Is it possible to remove `gfold-bin` and keep `gfold` and `gfold-git`? Thank you.

**Comment by orhun** [comment]
Sure, done.
