### ISSUE TITLE
Question: gfold `1.1.0` returns to using a single crate repostiory, does anything need to be changed?

### ISSUE THREAD

**Issue by nickgerace** [orhun/PKGBUILDs#6]
gfold `1.0.0` to `1.0.4` used the cargo workspaces feature to handle having two sub crates in one repository. With `gfold 1.1.0`, the repository returns to a single crate structure. (apologies for the reverted repository structure in such short time!)

Since [there was an issue encountered](https://github.com/nickgerace/gfold/issues/107) when `gfold` switched from a single crate repository to a cargo workspace-oriented/multi-crate repository previously, will there be an issue now that the repository has switched _back_?

Release tag: https://github.com/nickgerace/gfold/releases/tag/1.1.0
Release tree: https://github.com/nickgerace/gfold/tree/1.1.0

**Comment by orhun** [comment]
Hey!

No, there's no issue. Everything builds/works fine. I removed the flag that builds only the `gfold` before. (`--package gfold`)

`1.1.1` is now in the AUR.

Thank you for reaching out and letting me know.
Keep experimenting ;)

**Comment by nickgerace** [comment]
Thanks @orhun  :)
