### ISSUE TITLE
`dra` 0.4.0 release asset name change

### ISSUE THREAD

**Issue by devmatteini** [orhun/PKGBUILDs#8]
Hi!

I wanted to let you know that in the [latest release](https://github.com/devmatteini/dra/releases/tag/0.4.0) of `dra` I changed the `.tar.gz` for linux asset name.

Old name: `dra-0.3.8.tar.gz`
New name: `dra-0.4.0-x86_64-unknown-linux-gnu.tar.gz`

**Comment by orhun** [comment]
Yup, already been updated: https://github.com/orhun/PKGBUILDs/commit/9456ab81db3ecdf4036b30018f77109227ae8e0a

Thanks for letting me know! 🐻
