### ISSUE TITLE
Question: How did you create the apikey.crypt file

### ISSUE THREAD

**Issue by 0x61nas** [orhun/PKGBUILDs#9]
I wanna use `nvchecker` to manage my PKGBUILDs. I've seen ur configuration and I like the way that you manage the API keys with
But I don't know how I can duplicate this, what tool that u use to encrypt the API keys file? is gpg? and if it's, how? and how `nvchecker` decrypt it

**Comment by orhun** [comment]
Hey!
I'm using [`git-crypt`](https://github.com/AGWA/git-crypt) to encrypt the API key file. So it is plaintext on my PC but encrypted on the git repository. It is pretty straightforward!

**Comment by 0x61nas** [comment]
very useful info, thanks for ur reply
